name: Pystaff
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiobotocore=2.25.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.1=pyh2a7be5b_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - arviz=0.22.0=pyhcf101f3_1
  - asteval=1.0.6=pyhd8ed1ab_0
  - astropy=7.1.1=pyhd8ed1ab_0
  - astropy-base=7.1.1=py314h7d719a5_0
  - astropy-iers-data=0.2025.10.20.0.39.8=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - botocore=1.40.49=pyhd8ed1ab_0
  - bottleneck=1.6.0=py314hdcf55e8_1
  - bqplot=0.12.45=pyhe01879c_0
  - brotli-python=1.1.0=py314he8615de_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h44086f9_1
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h6b18a25_2
  - corner=2.2.3=pyhd8ed1ab_1
  - cpython=3.14.0=py314hd8ed1ab_102
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.17=py314hac9ea21_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - docutils=0.22.2=pyhd8ed1ab_0
  - emcee=3.1.6=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.60.1=py314h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.8.0=py314h50f4ffc_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gast=0.4.0=pyh9f0ad1d_0
  - gflags=2.2.2=hf9b8971_1005
  - glib=2.86.0=hc66c15f_1
  - glib-tools=2.86.0=hb9d6e3a_1
  - glog=0.7.1=heb240a5_0
  - gst-plugins-base=1.24.11=h3c5c1d0_0
  - gstreamer=1.24.11=hfe24232_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py314h1c8d760_100
  - hdf5=1.14.6=nompi_he65715a_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipydatagrid=1.4.0=pyhcf101f3_2
  - ipykernel=7.0.1=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jplephem=2.23=pyha4b2019_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py314hb140f16_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libarrow=21.0.0=hce8344c_9_cpu
  - libarrow-acero=21.0.0=hc317990_9_cpu
  - libarrow-compute=21.0.0=h75845d1_9_cpu
  - libarrow-dataset=21.0.0=hc317990_9_cpu
  - libarrow-substrait=21.0.0=h144af7f_9_cpu
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libclang-cpp18.1=18.1.8=default_h73dfc95_15
  - libclang13=21.1.4=default_h6e8f826_0
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libfabric=2.3.1=hce30654_1
  - libfabric1=2.3.1=hc919400_1
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=he69a767_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - libllvm18=18.1.8=default_h3f38c9c_10
  - libllvm21=21.1.4=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_2
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libopus=1.5.2=h48c0fde_0
  - libparquet=21.0.0=h0ac143b_9_cpu
  - libpmix=5.0.8=h3e7ebac_2
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.0=h31f7a3a_0
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.08.12=h91c62da_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h7dc4979_0
  - libutf8proc=2.11.0=hc25f550_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - lmfit=1.3.4=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h286801f_1
  - m2r=0.3.1=pyhd8ed1ab_1
  - matplotlib=3.10.7=py314he55896b_0
  - matplotlib-base=3.10.7=py314hd63e3f0_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - mpi=1.0.1=openmpi
  - mpi4py=4.1.1=py314ha404a82_101
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.1.0=py314h75312c3_0
  - multiprocess=0.70.18=py314h9d33bd4_2
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - nspr=4.37=h31e89c2_0
  - nss=3.117=h1c710a3_0
  - numpy=2.3.4=py314h5b5928d_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openmpi=5.0.8=h65ea042_108
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha3d490a_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py314haf93fec_3
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - pockets=0.9.1=pyhd8ed1ab_1
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=pyhe1237c8_0
  - psutil=7.1.1=py314h0612a62_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py2vega=0.6.1=pyhd8ed1ab_0
  - pyarrow=21.0.0=py314he55896b_1
  - pyarrow-core=21.0.0=py314hf20a12a_1_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyerfa=2.0.1.5=py310hbb12772_2
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py314h17b549b_2
  - pyqt5-sip=12.17.0=py314h93ecee7_2
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.14.0=h40d2674_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py314hf107ba7_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - qt-main=5.15.15=h9b65787_6
  - re2=2025.08.12=h64b956e_1
  - readline=8.2=h1d1bf99_2
  - s3fs=2025.9.0=pyhd8ed1ab_0
  - schwimmbad=0.4.2=py314h4dc9dd8_2
  - scipy=1.16.2=py314h624bdf2_0
  - setuptools=80.9.0=pyhff2d567_0
  - setuptools-scm=9.2.2=pyhd8ed1ab_0
  - sip=6.14.0=py314h93ecee7_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx_rtd_theme=0.4.3=pyhd3eb1b0_0
  - sphinxcontrib-napoleon=0.7=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h892fb3f_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py314hb84d1df_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.3=pyh332efcf_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - uncompresspy=0.4.1=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.0=py314h75312c3_0
  - xarray=2025.11.0=pyhcf101f3_0
  - xarray-einstats=0.9.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=pyh7db6752_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.25.0=py314h163e31d_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
    - capfit==2.7.1
    - ppxf==9.4.2
prefix: /Users/tbarone/opt/anaconda3/envs/Pystaff
